// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpDClfwBVRoOtCyKbnxo1SuiIhUjXlklI',
    appId: '1:474880422616:web:141428972ff98fcf8f9dad',
    messagingSenderId: '474880422616',
    projectId: 'codepie-1eb26',
    authDomain: 'codepie-1eb26.firebaseapp.com',
    storageBucket: 'codepie-1eb26.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATw_NYbQzRQUfjogW07JZRH11D5OR6MT8',
    appId: '1:474880422616:android:ca6d32d9bc88640f8f9dad',
    messagingSenderId: '474880422616',
    projectId: 'codepie-1eb26',
    storageBucket: 'codepie-1eb26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZWnOYQh6aEdjPCDfixI0E1b2faDPLF5U',
    appId: '1:474880422616:ios:6e2172cc48193a838f9dad',
    messagingSenderId: '474880422616',
    projectId: 'codepie-1eb26',
    storageBucket: 'codepie-1eb26.appspot.com',
    iosBundleId: 'com.example.mypersonelnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZWnOYQh6aEdjPCDfixI0E1b2faDPLF5U',
    appId: '1:474880422616:ios:6e2172cc48193a838f9dad',
    messagingSenderId: '474880422616',
    projectId: 'codepie-1eb26',
    storageBucket: 'codepie-1eb26.appspot.com',
    iosBundleId: 'com.example.mypersonelnotes',
  );
}
